### ISSUE TITLE
Finalize features specification

### ISSUE THREAD

**Issue by neginhashmati** [DIT112-V20/group-06#108]
## User story
As an open source developer, I want to have an accurate list of features that the SmartCar has so that I know what it is included with the system. 

## Acceptance criteria
The features specification has been finalized and updated in the Wiki.

**Comment by platisd** [comment]
> As a user

Generally using "a user" as the subject of your user story is rather weak. It's better to be more specific. In this case, I would argue that the users care about your written specification.
However, **open source developers** who may consider picking up this project and continue its development probably do care! :)

**Comment by neginhashmati** [comment]
Thank you for your suggestion, we will change the user story to make it clearer. :)

**Comment by JenniNord** [comment]
https://github.com/DIT112-V20/group-06/milestones
