### ISSUE TITLE
UI Prototype version 1

### ISSUE THREAD

**Issue by Victori4** [DIT112-V20/group-06#11]
## User story
* As a DJ, I want the app to be simple to use so that I can get the car moving easily.

## Acceptance criteria
* Version 1 of the UI prototype is ready for testing.

**Comment by JenniNord** [comment]
**Link to dynamic prototype:** https://www.figma.com/proto/Lx9D2WlgJAJgMgJIuNUlqa/UI-prototype-1?node-id=10%3A25&scaling=scale-down
