### ISSUE TITLE
Write wiki page with ideas for future development

### ISSUE THREAD

**Issue by FayonaC** [DIT112-V20/group-06#111]
## User story

As an open source developer, I want to read about the possibilities of future implementations of DJ SmartCar so that I can get inspired.  

## Acceptance criteria
There is a Wiki page with possible ideas for further development.

**Comment by JenniNord** [comment]
https://github.com/DIT112-V20/group-06/wiki/Ideas-for-Further-Development-of-DJ-SmartCar
