### ISSUE TITLE
The car performs a chosen dance move

### ISSUE THREAD

**Issue by FayonaC** [DIT112-V20/group-06#12]
## User story 
As a person that needs cheering up, I want the car to perform a chosen dance move so that I will be entertained.

## Acceptance criteria
The car can perform the following dance moves:
* ‘Shake’ - moves forward and backwards in a V shape
* [Tank turn](https://youtu.be/yzwM8KE2L3I)/pirouette/spin - car spins 360 degrees continuously
* Shuffle - moves forwards and backwards repeatedly

### ‘Shake’
1. Rotate left 45 degrees
    Go back 30 cm
2. Go forward 30 cm
3. Rotate 45 degrees right
   Go back 30 cm
4. Go forward 30 cm
5. Puts "steps" back 1 and adds a "repeat" or finishes dance after repeating 3 times
(Repeat all steps three times)

### Shuffle
1. Move forwards until distance == 20 cm
2. Go backwards until distance == 10 cm
3. Move forwards until distance == 30 cm
4. Move backwards until distance == 10 cm
5. Go forwards until distance == 20 cm
6. Move backwards until distance == 0 cm

**Comment by JenniNord** [comment]
Work on one dance move together, then split up into 2 groups to complete the last 2 dance moves.

*__Edit:__ We will work on all dances together instead.*
