### ISSUE TITLE
UI Prototype version 2

### ISSUE THREAD

**Issue by JenniNord** [DIT112-V20/group-06#29]
## User story
As an app user, I want a second version of the UI prototype so that it incorporates feedback from testers.

## Acceptance criteria
* Version 2 of the UI prototype is ready for testing.

**Comment by FayonaC** [comment]
Link to the dynamic prototype:

https://www.figma.com/proto/Lx9D2WlgJAJgMgJIuNUlqa/UI-prototype?node-id=153%3A62&scaling=min-zoom
