### ISSUE TITLE
Features Specification

### ISSUE THREAD

**Issue by shonaighdouglas** [DIT112-V20/group-06#4]
*Placeholder*

**Comment by JenniNord** [comment]
List of milestones:
https://github.com/DIT112-V20/group-06/milestone/1
https://github.com/DIT112-V20/group-06/milestone/2
https://github.com/DIT112-V20/group-06/milestone/3
https://github.com/DIT112-V20/group-06/milestone/4
https://github.com/DIT112-V20/group-06/milestone/5
