### ISSUE TITLE
Testing UI Prototype V2

### ISSUE THREAD

**Issue by shonaighdouglas** [DIT112-V20/group-06#42]
## User story

- As a user, I want the second version of the UI prototype to be tested so that I know it will be easy to use.

## Acceptance criteria: 

- At least 10 users have completed all test tasks.  (Done by Thursday noon)

**Comment by neginhashmati** [comment]
The results for the testing can be found in the wiki page: https://github.com/DIT112-V20/group-06/wiki/UI-Prototypes-and-Testing
